### ISSUE TITLE
the current method of configing sysctl setting is exteramly slow

### ISSUE THREAD

**Issue by SeanMooney** [openstack-k8s-operators/edpm-ansible#254]
https://github.com/openstack-k8s-operators/edpm-ansible/blob/27376723517bdf5ecec263e7560d89ed85796cf1/roles/edpm_kernel/tasks/main.yml#L71-L83

the current apptoch updates each settign oen at a time

so this restuls in (n key * m host) executions.

since does not change per host this can be reduced to a n called by delegating
to the first host in the group and then copying to the rest.

it can be further optimeised by moving the rendering of the file into the jinja template

https://github.com/openstack-k8s-operators/edpm-ansible/blob/main/roles/edpm_kernel/templates/edpm-sysctl.conf.j2

which already has been done.

so the existing call
```
- name: Set extra sysctl options
      ansible.posix.sysctl:
        name: "{{ setting.key }}"
        value: "{{ setting.opt.value }}"
        sysctl_set: "{{ setting.opt.set | default(true) }}"
        state: "{{ setting.opt.state | default('present') }}"
        sysctl_file: "/etc/sysctl.d/99-edpm.conf"
        reload: false
      loop: "{{ edpm_kernel_sysctl_settings | combine(edpm_kernel_sysctl_extra_settings) | dict2items(key_name='key', value_name='opt') }}"
      loop_control:
        label: "{{ setting.key }}"
        loop_var: setting
      register: _extra_sysctl_result
```
can just be replaced with
```
- name: apply sysctl options
  become
  ansible.builtin.command: "sysctl -p"
```

or perhaps we can invoke the ansible.posix.sysctl once with the file.
